/*CREAR BBDD 'PRIMER REPASO' CON LAS SIGUIENTES CARACTERISTICAS:
		a- ARCHIVO PRIMARIO DE DATOS CON 20MB DE TAMAÑO INCIAL, SIN LIMITE E INCREMENTE DE 20MB
		b- UN GRUPO DE ARCHIVOS LLAMADO 'EUROPA' CON DOS ARCHIVOS DE DATOS, DE 10MB DE TAMAÑO INICIAL, 
			MAXIMO DE 100MB E INCREMNETO DE 10MB
		c- UN GRUPO DE ARCHIVOS  LLAMADO 'AUSTRALIA' CON UN UNICO ARCHIVO DE DATOS CON 250MB DE TAMAÑO INICIAL
			SIN LIMITE E INCRIMENTOS DE 50MB
		d- CREA DOS ARCHIVOS LOG DE 33MB DE TAMAÑO INICIAL MAXIMO DE 250MB E INCREMENTETOS DE 33MB  */


		-- DROP DATABASE PrimerRepaso; --Eliminar BBDD

CREATE DATABASE [PrimerRepaso]
ON PRIMARY
(NAME =N'Primer_repaso' , FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Primer_repaso.mdf',
SIZE = 20MB, MAXSIZE = UNLIMITED, FILEGROWTH = 20MB),
FILEGROUP Europa
(NAME =N'Europa1' , FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Europa1.mdf',
SIZE = 10MB, MAXSIZE = 100MB, FILEGROWTH = 10MB),
(NAME =N'Europa2' , FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Europa2.mdf',
SIZE = 10MB, MAXSIZE = 100MB, FILEGROWTH = 10MB),
FILEGROUP Australia
(NAME =N'Australia1' , FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Australia1.mdf',
SIZE = 250MB, MAXSIZE = UNLIMITED, FILEGROWTH = 50MB)
LOG ON
(NAME = N'Primer_repaso_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Primer_repaso_log.ldf',
SIZE = 33MB, MAXSIZE = 250MB, FILEGROWTH = 33MB),
(NAME = N'Primer_repaso2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Primer_repaso2_log.ldf',
SIZE = 33MB, MAXSIZE = 250MB, FILEGROWTH = 33MB);/*
------------------------------------------------------------------------------------------------------------------------

2- AÑADE UN GRUPO MAS LLAMADO ‘COPIAS’ 
3- AÑADE A ESTE GRUPO UN ARCHIVO DE DATOS Y CREA UN LOG DE 5MB DE TAMAÑO INICIAL, SIN LIMITE E INCREMENTOS DE 10MB
4- CREA UNA TABLA LLAMADA ‘COPIA’ DENTRO DEL GRUPO ‘COPIA’ , QUE TENGA CODIGO(INT PK) Y FECHA(DATE NOT NULL) */

ALTER DATABASE PrimerRepaso
ADD FILEGROUP Copias;

ALTER DATABASE PrimerRepaso
ADD FILE
(NAME =N'Copias1' , FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Copias1.mdf',
SIZE = 5MB, MAXSIZE = UNLIMITED, FILEGROWTH = 10MB)
TO FILEGROUP Copias;

ALTER DATABASE PrimerRepaso
ADD LOG FILE
(NAME =N'Primer_repaso3_log' , FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Primer_repaso3_log.ldf',
SIZE = 5MB, MAXSIZE = UNLIMITED, FILEGROWTH = 10MB); 

USE PrimerRepaso
	CREATE TABLE COPIA(
	ID INT PRIMARY KEY,
	Nombre varchar(50)
	)ON Copias/*
-------------------------------------------------------------------------------------------------------------

5.	AÑADE UN SEGUNDO ARCHIVO AL GRUPO ‘COPIA’ , CON LOS TAMAÑOS QUE QUIERAS
6.	ELIMINA ESTE ULTIMO ARCHIVO LOG
7.	MODIFICA EL PRIMER ARCHIVO DE DATOS DE ‘AUSTRALIA’ Y PONLE UN TAMAÑO MAXIMO DE 100MB */

ALTER DATABASE PrimerRepaso
ADD FILE
(NAME =N'Copias2' , FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Copias2.mdf',
SIZE = 5MB, MAXSIZE = UNLIMITED, FILEGROWTH = 10MB)
TO FILEGROUP Copias;

-- ALTER DATABASE PrimerRepaso REMOVE FILE Primer_repaso3_log; 

ALTER DATABASE PrimerRepaso
MODIFY FILE
(NAME = 'Australia1', 
MAXSIZE = 100MB); /*
---------------------------------------------------------------------------------------------------------------

8.	CREA UNA TABLA ‘TEMP’ CON (CÓDIGO INT, NOMBRE VARCHAR(50)) 
9.	ESTABLECE EL CAMPO CÓDIGO COMO CLAVE PRINCIPAL
10.	INSERTA DATOS DE TRES FORMA DIFERENTES
11.	ELIMINA LOS DATOS
12.	ELIMINA LA TABLA */

USE PrimerRepaso;

CREATE TABLE TEMP(
	CODIGO INT,
	Nombre varchar(50)
);
	
ALTER TABLE TEMP ALTER COLUMN CODIGO INT NOT NULL ; -- Primero, NOT NULL
ALTER TABLE TEMP ADD PRIMARY KEY (CODIGO); 

INSERT INTO dbo.TEMP VALUES (1,'Juan'); 
INSERT INTO dbo.TEMP VALUES (5,null),(6,Null); 
INSERT INTO dbo.TEMP VALUES (2, NULL); 
INSERT INTO dbo.TEMP (CODIGO) VALUES (4); 
INSERT INTO dbo.TEMP (CODIGO,Nombre) VALUES (3,'Mercedes'); 

SELECT * FROM TEMP; 

-- DELETE TEMP
-- DROP TABLE TEMP; 
/*
------------------------------------------------------------------------------------------------

13.	CREA UNA TABLA ‘HABITACIONES’ CON (ID INT PK AUTONUMERICO , TIPO VARCHAR (50) NOT NULL )
14.	AÑADE EL CAMPO PRECIO DE HABITACIONES INT NOT NULL
15.	MODIFICA EL CAMPO PRECIO PARA QUE SEA FLOAT
16.	INSERTA TRES REGISTROS EN LA TABLA HABITACIONES
17.	CREA UNA TABLA LLAMADA RESERVAS CON (ID_RESERVA INT PK, ID CLIENTE INT NOT NULL, ID_HABITACION INT NOT NULL,FECHA NULL) */

CREATE TABLE HABITACIONES(
	ID INT PRIMARY KEY IDENTITY,
	TIPO VARCHAR(50) NOT NULL
);

ALTER TABLE dbo.HABITACIONES ADD PRECIO INT NOT NULL;

ALTER TABLE HABITACIONES ALTER COLUMN PRECIO FLOAT NOT NULL;

INSERT INTO HABITACIONES VALUES ('Doble',100); 
INSERT INTO HABITACIONES VALUES ('Triple',120.20); 
INSERT INTO HABITACIONES VALUES ('Sencilla',90.5);

CREATE TABLE RESERVAS (ID_RESERVA INT PRIMARY KEY, ID_CLIENTE INT NOT NULL, ID_HABITACION INT NOT NULL,FECHA DATE NULL) /*
-------------------------------------------------------------------------------------------------------------------------

18.	CREA UNA RELACION ENTRE LAS DOS TABLAS
19.	ELIMINA LA RELACION
20.	VUELVE  A CREAR LA RELACION
21.	INSERTA REGISTROS EN LA TABLA RESERVAS
22.	MODIFICA EL CAMPO TIPO DE LA TABLA HABITACIONES PARA QUE SU VALOR POR DEFECTO SEA ‘SUITE’
23.	CREA UN INDICE PARA EL CAMPO ID_CLIENTE DE LA TABLA RESERVAS */

ALTER TABLE RESERVAS ADD CONSTRAINT FK_Reserva_Habitaciones FOREIGN KEY (ID_HABITACION) REFERENCES HABITACIONES (ID);

--ALTER TABLE  dbo.RESERVAS DROP CONSTRAINT  FK_Reserva_Habitaciones;
SELECT * FROM RESERVAS; 

INSERT INTO RESERVAS VALUES (4,2,1,'25-09-1973'); 
INSERT INTO RESERVAS VALUES (5,2,3,'25-09-1973'); 
INSERT INTO RESERVAS VALUES (6,1,1,'25-09-1973'); 

ALTER TABLE HABITACIONES ADD DEFAULT 'SUITE' FOR TIPO; 

CREATE INDEX Indice ON RESERVAS (ID_CLIENTE ASC);   


------------------------------------------------ 
/*
	Base de Datos: PRIMER_REPASO
	Tenemos el departamento: Ejercicios
	Ejericios – las dos tablas 
	Dirección – Todas
	En el departamento Ejercicios hay un tipos de trabajador (Alumno)
	Alumno puede hacer de todo menos borrar 
	Desde Dirección quieren poder hacer todo en cualquier tabla

	Login: Trabajador --->  usuario alumno
	Login: Dire_repaso ---> usuario Boss */

	USE PrimerRepaso
	GO
	
	CREATE LOGIN Trabajador WITH PASSWORD = '12345', DEFAULT_DATABASE = [PrimerRepaso];
	CREATE LOGIN Dire_repaso WITH PASSWORD = '12345', DEFAULT_DATABASE = [PrimerRepaso];

	CREATE SCHEMA Ejercicios;

	create USER Alumno FOR LOGIN Trabajador WITH DEFAULT_SCHEMA = Ejercicios;
	create USER Boss FOR LOGIN Dire_repaso WITH DEFAULT_SCHEMA = dbo;

	ALTER SCHEMA Ejercicios TRANSFER dbo.HABITACIONES;
	ALTER SCHEMA Ejercicios TRANSFER dbo.RESERVAS;

	GRANT INSERT, UPDATE, SELECT, CONTROL,MODIFY ON SCHEMA :: EJERCICIOS TO ALUMNO; --TODO MENOS BORRAR

	CREATE ROLE GERENCIA;

	ALTER ROLE GERENCIA ADD MEMBER BOSS;
	
	GRANT SELECT, UPDATE, DELETE, INSERT, CONTROL, ALTER ON DATABASE :: [PrimerRepaso] TO Boss; -- Dar permisos BBDD


